### ISSUE TITLE
Message to John000708

### ISSUE THREAD

**Issue by jordanwilliams1** [John000708/Barrels#1]
@John000708 Sorry. Didn't know how to PM you. Could you look at the slimefun backpacks? They seem to be broken on github. I Think its to do with the & changes that were made.

**Comment by John000708** [comment]
Thank you for letting me know. It has been fixed.

**Comment by jordanwilliams1** [comment]
@John000708 Would there any chance you can add me on skype? I See your active on slimefun and we run  the plugin on our server. It would be handy to be able to tell you bugs if we find any. My skype: thepotatoarmyhd

**Comment by John000708** [comment]
@jordanwilliams1 I'd prefer to contact me through bukkit. My username is also John000708.
