### ISSUE TITLE
Barrels not putting items into barrel inventory

### ISSUE THREAD

**Issue by chloeseitz27** [John000708/Barrels#15]
### Description (Required)
Items are not stored in barrels, just eaten up when put in the block. They do not drop on the floor when broken. The item is set as the barrel "item type" but no items are actually stored.

I'm not sure if this matters, but I only noticed the errors after I put a Biometric Protection on a barrel and registered it with an ID card. That barrel still works, but unrelated barrels placed by myself or other players don't work.

### Steps to reproduce the Issue (Required)
Place down a barrel and try to put any amount of items in. They do not show up as available to be withdrawn and they don't drop on the floor when the barrel is broken.

### Expected behavior (Required)
Items to be stored as normal

### Server Log / Error Report
https://pastebin.com/2afFZgSu

### Environment (Required)
In error report

**Comment by TheBusyBiscuit** [comment]
Update Barrels, Slimefun and CS-CoreLib.
Then it should work.
