### ISSUE TITLE
Cannot get items out of barrels

### ISSUE THREAD

**Issue by cybermancerr** [John000708/Barrels#19]
Error generated by Slimefun: https://pastebin.com/zJdkxNuQ

Java Environment:
  Operating System: Linux
  Java Version: 1.8.0_242

Server Software: Paper
  Build: git-Paper-84 (MC: 1.15.2)
  Minecraft: 1.15.2-R0.1-SNAPSHOT

Slimefun Environment:
  CS-CoreLib vDEV - 80 (git e3242c60)
  Slimefun vDEV - 414 (git d37b1504)

Installed Addons (13)
  + Barrels DEV - 8 (git 447cb487)
  + SlimeXpansion DEV - 4 (git 5bf10c29)
  + ExtraGear DEV - 3 (git de222ab7)
  + HotbarPets DEV - 23 (git 37b50104)
  + ExoticGarden DEV - 25 (git b5fce971)
  + SoulJars DEV - 10 (git 58202ab6)
  + SlimefunOreChunks DEV - 3 (git 7ddf966e)
  + SlimefunOres 1.4.6
  + ElectricSpawners DEV - 6 (git 845b6076)
  + ExtraHeads DEV - 9 (git 32435a1f)
  + SlimyTreeTaps DEV - 5 (git 6dd80630)
  + PrivateStorage DEV - 8 (git 6b242fc5)
  + DyedBackpacks DEV - 1 (git 4b4d1f0f)

Installed Plugins (71):
  + PlaceholderAPI 2.10.4
  + RealDualWield 1.1.27
  + OldCombatMechanics 1.7.5BETA
  + HubCommand 1.1
  + LagAssist 2.20.1
  + WorldEdit 7.1.0;8e55131
  + OpenInv 4.0.8
  + MineableSpawners 2.0.8
  + SkinnerLibs 1.0-SNAPSHOT
  + ClearLag 3.1.0
  + WorldBorder 1.9.10 (beta)
  + Votifier 2.6.0-SNAPSHOT
  + NightVision 2.0
  + VotingPlugin 5.20.5
  + AsyncWorldEdit 3.6.18
  + Minepacks 2.1.5-Release
  + PermissionsEx 1.23.4
  + LimitPillagers 2.12.0
  + NerfPhantoms 1.2.0
  + CS-CoreLib DEV - 80 (git e3242c60)
  + Vault 1.7.2-b107
  + ProtocolSupport 4.29-dev
  + Cannons 2.5.5
  + WorldGuard 7.0.2-SNAPSHOT;bf2593e
  + Slimefun DEV - 414 (git d37b1504)
  + Barrels DEV - 8 (git 447cb487)
  + ViaVersion 2.2.3
  + ViaBackwards 2.4.0-SNAPSHOT
  + SlimeXpansion DEV - 4 (git 5bf10c29)
  + Essentials 2.17.1.52
  + ExtraGear DEV - 3 (git de222ab7)
  + SafeTrade 1.1.0
  + ProtocolLib 4.5.1-SNAPSHOT-b445
  + LibsDisguises 9.8.9-SNAPSHOT
  + MythicDrops 5.1.2-5e3274b
  + DiscordSRV 1.18.4
  + HotbarPets DEV - 23 (git 37b50104)
  + EssentialsChat 2.17.1.52
  + ExoticGarden DEV - 25 (git b5fce971)
  + TimeIsMoney 1.9.6.11
  + KeepChunks 1.6.2
  + XPBoost 3.3.0
  + mcMMO 2.1.114
  + SoulJars DEV - 10 (git 58202ab6)
  + ViaRewind 1.4.5
  + EnjinMinecraftPlugin 3.5.7
  + SlimefunOreChunks DEV - 3 (git 7ddf966e)
  + SlimefunOres 1.4.6
  + ElectricSpawners DEV - 6 (git 845b6076)
  + Movecraft 7.0.0_beta_2
  + HolographicDisplays 2.4.1
  + ExtraHeads DEV - 9 (git 32435a1f)
  + SlimyTreeTaps DEV - 5 (git 6dd80630)
  + PrivateStorage DEV - 8 (git 6b242fc5)
  + DyedBackpacks DEV - 1 (git 4b4d1f0f)
  + AAC 4.3.5
  + AuctionHouse 2.0.0
  + Factions 1.6.9.5-U0.5.7-b215
  + MythicMobs 4.9.0-SNAPSHOT-3186
  + JetsMinions 5.6.15
  + EssentialsSpawn 2.17.1.52
  + CratesPlus 4.5.2
  + WorldGuardExtraFlags 4.1.2
  + MyPet 3.1
  + ChatControl 8.5.4
  + Jobs 4.15.2
  + RandomTP 1.0.7.2
  + ActionHealth 3.4.2
  + Skinner 4.2.0
  + RPGHealthPlus 1.4.8
  + CrazyEnvoy 1.3.8-RELEASE

**Comment by KillerXCoder** [comment]
same problem, latest build -> https://imgur.com/a/pwcG4w8 but i am not getting any errors in console
