### ISSUE TITLE
hologram

### ISSUE THREAD

**Issue by 100petr** [John000708/Barrels#24]
![2020-05-03_21 47 17](https://user-images.githubusercontent.com/29830635/80924205-f04e8300-8d87-11ea-9d08-56ec9c7043f8.png)
After destroying the barrel, the item with the hologram remains

/sf versions:
https://pastebin.com/CqwAWJ7H

**Comment by jobogamer24** [comment]
I have the same issue.

**Comment by MrWardy** [comment]
Same here

**Comment by Cyber-MC** [comment]
> Same here



> I have the same issue.



> ![2020-05-03_21 47 17](https://user-images.githubusercontent.com/29830635/80924205-f04e8300-8d87-11ea-9d08-56ec9c7043f8.png)
> After destroying the barrel, the item with the hologram remains
> 
> /sf versions:
> https://pastebin.com/CqwAWJ7H

The entity despawns.

**Comment by bobhenl** [comment]
Same here... @John000708 @TheBusyBiscuit

**Comment by TheBusyBiscuit** [comment]
Why was I tagged here...

**Comment by 100petr** [comment]
fixed in the latest version, I close this.
