### ISSUE TITLE
[Spigot 1.16+] Putting any item into a barrel adds an empty line of lore to it

### ISSUE THREAD

**Issue by ghost** [John000708/Barrels#28]
Due to *`LORE_DATA`* in Barrel.java being mostly invalid formatting code, it gets truncated to `"§e§l"` rather than `"§b§a§r§r§e§l"`. This causes the empty line in the lore and leads to `updateBarrel()` never finding lore that matches *`LORE_DATA`*, which means the blank line is never removed. It's a simple fix, either remove the invalid parts of *`LORE_DATA`* or change it to something else entirely without using invalid formatting codes.

**Comment by 100petr** [comment]
![Screenshot_20200715-183122_Discord](https://user-images.githubusercontent.com/29830635/87570897-93e1db00-c6c9-11ea-819a-e9078ce7cde3.jpg)
From sf discord.

**Comment by TheBusyBiscuit** [comment]
Fixed.
